# Spring Boot application configuration.
spring:
  application:
    name: research
  # Database settings.
  datasource:
    url: jdbc:h2:file:./data/research-health-project-db;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  # Web server settings.
  server:
    port: 8080
  # SQL initialization.
  sql:
    init:
      mode: embedded
  # JPA/Hibernate.
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        '[format_sql]': true
        '[use_sql_comments]': true
  # H2 console.
  h2:
    console:
      enabled: true
      path: /h2-console
  # GraphQL
  graphql:
    graphiql:
      enabled: true

# Logging configuration.
logging:
  file:
    name: logs/app.log
    max-size: 10MB
    max-history: 5
  level:
    root: DEBUG
    '[org.hibernate.sql]': DEBUG
    '[org.hibernate.type.descriptor.sql.BasicBinder]': TRACE
    '[org.hibernate.tool.hbm2ddl]': DEBUG
    '[org.springframework.graphql]': DEBUG