/* 1. DROP existing tables, in dependency order. */
DROP TABLE IF EXISTS researcher_article CASCADE;
DROP TABLE IF EXISTS researcher_emails CASCADE;
DROP TABLE IF EXISTS researchers CASCADE;
DROP TABLE IF EXISTS reviewer_article CASCADE;
DROP TABLE IF EXISTS reviewer_emails CASCADE;
DROP TABLE IF EXISTS reviewers CASCADE;
DROP TABLE IF EXISTS reviews CASCADE;
DROP TABLE IF EXISTS articles CASCADE;
/* 2. CREATE tables */
CREATE TABLE articles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255),
    subject VARCHAR(255),
    content VARCHAR(255),
    published_date DATE
);
CREATE TABLE researchers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    title VARCHAR(255),
    affiliation VARCHAR(255)
);
CREATE TABLE reviewers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    title VARCHAR(255),
    affiliation VARCHAR(255)
);
CREATE TABLE reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255),
    content VARCHAR(255),
    rating INTEGER,
    decision VARCHAR(10),
    -- enum('ACCEPT','REJECT','REVISION')
    article_id BIGINT,
    reviewer_id BIGINT
);
CREATE TABLE researcher_article (
    article_id BIGINT NOT NULL,
    researcher_id BIGINT NOT NULL,
    PRIMARY KEY (article_id, researcher_id)
);
CREATE TABLE reviewer_article (
    article_id BIGINT NOT NULL,
    reviewer_id BIGINT NOT NULL,
    PRIMARY KEY (article_id, reviewer_id)
);
CREATE TABLE researcher_emails (
    researcher_id BIGINT NOT NULL,
    emails VARCHAR(255)
);
CREATE TABLE reviewer_emails (
    reviewer_id BIGINT NOT NULL,
    emails VARCHAR(255)
);
/* 3. Foreign-key constraints */
-- research -> articles
ALTER TABLE researcher_article
ADD CONSTRAINT FK_RESEARCHER_ARTICLE_ARTICLE_ID FOREIGN KEY (article_id) REFERENCES articles(id);
ALTER TABLE researcher_article
ADD CONSTRAINT FK_RESEARCHER_ARTICLE_RESEARCHER_ID FOREIGN KEY (researcher_id) REFERENCES researchers(id);
ALTER TABLE researcher_emails
ADD CONSTRAINT FK_RESEARCHER_EMAILS_RESEARCHER_ID FOREIGN KEY (researcher_id) REFERENCES researchers(id);
-- reviewer -> reviewers / articles
ALTER TABLE reviewer_article
ADD CONSTRAINT FK_REVIEWER_ARTICLE_ARTICLE_ID FOREIGN KEY (article_id) REFERENCES articles(id);
ALTER TABLE reviewer_article
ADD CONSTRAINT FK_REVIEWER_ARTICLE_REVIEWER_ID FOREIGN KEY (reviewer_id) REFERENCES reviewers(id);
ALTER TABLE reviewer_emails
ADD CONSTRAINT FK_REVIEWER_EMAILS_REVIEWER_ID FOREIGN KEY (reviewer_id) REFERENCES reviewers(id);
-- review -> article / reviewer
ALTER TABLE reviews
ADD CONSTRAINT FK_REVIEWS_ARTICLE_ID FOREIGN KEY (article_id) REFERENCES articles(id);
ALTER TABLE reviews
ADD CONSTRAINT FK_REVIEWS_REVIEWER_ID FOREIGN KEY (reviewer_id) REFERENCES reviewers(id);
/* 4. CHECK constraint for the "enum", optional, for those using H2. */
-- If you want to ensure that the `decision` column only contains allowed values:
ALTER TABLE reviews
ADD CONSTRAINT CK_REVIEWS_DECISION CHECK (decision IN ('ACCEPT', 'REJECT', 'REVISION'));