package local.health.research.dao;

import java.util.HashSet;
import java.util.List;
import java.util.Optional;

import org.springframework.stereotype.Repository;

import jakarta.persistence.EntityNotFoundException;
import jakarta.transaction.Transactional;
import local.health.research.inputs.ArticlePatch;
import local.health.research.models.Article;
import local.health.research.models.Researcher;
import local.health.research.models.Reviewer;
import local.health.research.repositories.ArticleRepository;

/**
 * ArticleDao is a data access object that encapsulates CRUD operations
 * for Article entities using Spring Data JPA. The class is annotated
 * with @Repository so that Spring recognizes it as a persistence
 * component and enables exception translation.
 */
@Repository
public class ArticleDao {

    // The JPA repository that actually talks to the database.
    private final ArticleRepository repository;

    // DAOs to resolve researcher and reviewer references.
    private final ResearcherDao researcherDao;
    private final ReviewerDao reviewerDao;

    /**
     * Constructs an ArticleDao and injects the required dependencies.
     *
     * @param repository    the ArticleRepository used for persistence
     * @param researcherDao helper DAO for researcher entities
     * @param reviewerDao   helper DAO for reviewer entities
     */
    public ArticleDao(
            ArticleRepository repository,
            ResearcherDao researcherDao,
            ReviewerDao reviewerDao) {
        this.repository = repository;
        this.researcherDao = researcherDao;
        this.reviewerDao = reviewerDao;
    }

    /**
     * Save an Article to the database.
     *
     * @param article the Article object to be persisted
     * @return the saved Article, which may contain an autogenerated id
     */
    public Article save(Article article) {
        return repository.save(article);
    }

    /**
     * Retrieve all Articles from the database.
     *
     * @return a List containing every Article entity
     */
    public List<Article> findAll() {
        return repository.findAll();
    }

    /**
     * Finds an Article by its primary key.
     *
     * @param id the unique identifier of the Article
     * @return an Optional containing the Article if it exists, otherwise empty
     */
    public Optional<Article> findById(Long id) {
        return repository.findById(id);
    }

    /**
     * Updates an Article using the fields provided in an ArticlePatch record.
     *
     * @param articleId the id of the Article to update
     * @param patch     the ArticlePatch containing optional fields
     * @return an Optional containing the updated Article
     */
    @Transactional
    public Optional<Article> update(Long articleId, ArticlePatch patch) {

        // 1. Retrieve the existing entity.
        Article article = repository.findById(articleId)
                .orElseThrow(() -> new EntityNotFoundException(
                        "Article with id " + articleId + " not found"));

        // 2. Update scalar fields (title, subject, content, publishedDate).
        if (patch.title() != null)
            article.setTitle(patch.title());
        if (patch.subject() != null)
            article.setSubject(patch.subject());
        if (patch.content() != null)
            article.setContent(patch.content());
        if (patch.publishedDate() != null)
            article.setPublishedDate(patch.publishedDate());

        // 3. Update many-to-many associations.

        // 3.1 - Researchers.
        if (patch.researcherIds() != null) {
            // 3a.i - Remove old association rows.
            repository.deleteResearcherAssociationsByArticleId(articleId);

            // 3.2 - Refresh the in-memory collection.
            patch.researcherIds()
                    .forEach(rid -> repository.addResearcherAssociation(articleId, rid));

            // 3.3 - Researcher.
            List<Researcher> newResearchers = researcherDao.findAllById(patch.researcherIds());
            article.setResearchers(new HashSet<>(newResearchers));
        }

        // 3.4 - Reviewers.
        if (patch.reviewerIds() != null) {
            repository.deleteReviewerAssociationsByArticleId(articleId);
            patch.reviewerIds()
                    .forEach(rid -> repository.addReviewerAssociation(articleId, rid));

            List<Reviewer> newReviewers = reviewerDao.findAllById(patch.reviewerIds());
            article.setReviewers(new HashSet<>(newReviewers));
        }

        // 4. Persist changes.
        Article updated = repository.save(article);
        // Optional but ensures that native queries are actually executed.
        repository.flush();

        return Optional.of(updated);
    }

    /**
     * Deletes an Article by its primary key.
     *
     * @param id the id of the Article to delete
     */
    public void deleteById(Long id) {
        repository.deleteById(id);
    }

    /**
     * Deletes the provided Article instance. The method performs the following:
     * 
     * @param article the Article entity to delete
     */
    @Transactional
    public void delete(Article article) {
        Long id = article.getId();
        // 1. Verify that the Article exists; if not, throw EntityNotFoundException.
        if (!repository.existsById(id)) {
            throw new EntityNotFoundException("Article not found: " + id);
        }

        // 2. Remove all rows in the researcher and reviewer join tables via native
        // queries.
        repository.deleteResearcherAssociationsByArticleId(id);
        repository.deleteReviewerAssociationsByArticleId(id);

        // 3. Clear bidirectional in-memory references to maintain consistency.
        Article managed = repository.findById(id).get();
        managed.getResearchers().clear();
        managed.getReviewers().clear();
        // 4. Persist the cleared entity to apply join-table deletions.
        repository.save(managed);

        // 5. Flush the repository to ensure all SQL statements are executed.
        repository.flush();

        // 6. Finally delete the Article record itself.
        repository.deleteById(id);
    }

    /**
     * Determines whether an Article with the specified id exists.
     *
     * @param id the id to check
     * @return true if the Article exists, false otherwise
     */
    public boolean existsById(Long id) {
        // Delegates to the underlying JpaRepository method.
        return repository.existsById(id);
    }
}
