package local.health.research.dao;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

import org.springframework.stereotype.Repository;

import local.health.research.models.Researcher;
import local.health.research.repositories.ResearcherRepository;

/**
 * ResearcherDao is a data access object that uses Spring Data JPA
 * to perform CRUD operations on Researcher entities.
 * The class is marked with @Repository so Spring recognizes it as a persistence
 * component.
 */
@Repository
public class ResearcherDao {

    // The JPA repository that actually performs the database operations.
    private final ResearcherRepository repository;

    /**
     * Constructor for ResearcherDao.
     *
     * Spring automatically injects the ResearcherRepository bean.
     *
     * @param repository the repository that talks to the database
     */
    public ResearcherDao(ResearcherRepository repository) {
        this.repository = repository;
    }

    /**
     * Persist a Researcher entity (insert or update).
     *
     * @param researcher the entity to be saved
     * @return the saved Researcher, possibly with an autogenerated id
     */
    public Researcher save(Researcher researcher) {
        return repository.save(researcher);
    }

    /**
     * Retrieve all Researcher entities from the database.
     *
     * @return a List containing every Researcher
     */
    public List<Researcher> findAll() {
        return repository.findAll();
    }

    /**
     * Find a single Researcher by its primary key.
     *
     * @param id the Researcher's unique identifier
     * @return an Optional holding the Researcher if found,
     *         otherwise Optional.empty()
     */
    public Optional<Researcher> findById(Long id) {
        return repository.findById(id);
    }

    /**
     * Delete a Researcher identified by its ID.
     *
     * @param id the primary key of the Researcher to delete
     */
    public void deleteById(Long id) {
        repository.deleteById(id);
    }

    /**
     * Retrieve multiple Researchers by a list of IDs.
     *
     * The method handles null or empty input by returning an empty list.
     * It then converts the Iterable returned by the repository into a List.
     *
     * @param researcherIds the list of Researcher IDs to fetch
     * @return a List of Researcher objects that match the given IDs
     */
    public List<Researcher> findAllById(List<Long> researcherIds) {
        if (researcherIds == null || researcherIds.isEmpty()) {
            return new ArrayList<>();
        }
        Iterable<Researcher> iterable = repository.findAllById(researcherIds);
        List<Researcher> result = new ArrayList<>();
        iterable.forEach(result::add);
        return result;
    }

    /**
     * Check if a Researcher exists for the given ID.
     *
     * @param id the primary key to check
     * @return true if a Researcher with that ID exists, false otherwise
     */
    public boolean existsById(Long id) {
        // Delegates directly to `JpaRepository`.
        return repository.existsById(id);
    }
}
