package local.health.research.dao;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

import org.springframework.stereotype.Repository;

import local.health.research.models.Reviewer;
import local.health.research.repositories.ReviewerRepository;

/**
 * ReviewerDao is a data-access object that uses Spring Data JPA
 * to perform CRUD operations on Reviewer entities.
 * The @Repository annotation tells Spring that this class
 * contains persistence logic and enables exception translation.
 */
@Repository
public class ReviewerDao {

    // The JPA repository that actually talks to the database.
    private final ReviewerRepository repository;

    /**
     * Constructor for ReviewerDao.
     *
     * Spring injects the ReviewerRepository bean automatically.
     *
     * @param repository the repository that handles Reviewer entities
     */
    public ReviewerDao(ReviewerRepository repository) {
        this.repository = repository;
    }

    /**
     * Persist a Reviewer entity (insert or update).
     *
     * @param reviewer the Reviewer to be saved
     * @return the saved Reviewer, possibly with an autogenerated id
     */
    public Reviewer save(Reviewer reviewer) {
        return repository.save(reviewer);
    }

    /**
     * Retrieve all Reviewer entities from the database.
     *
     * @return a List containing every Reviewer
     */
    public List<Reviewer> findAll() {
        return repository.findAll();
    }

    /**
     * Find a single Reviewer by its primary key.
     *
     * @param id the Reviewer's unique identifier
     * @return an Optional holding the Reviewer if found,
     *         otherwise Optional.empty()
     */
    public Optional<Reviewer> findById(Long id) {
        return repository.findById(id);
    }

    /**
     * Delete a Reviewer identified by its ID.
     *
     * @param id the primary key of the Reviewer to delete
     */
    public void deleteById(Long id) {
        repository.deleteById(id);
    }

    /**
     * Retrieve multiple Reviewers by a list of IDs.
     *
     * The method handles null or empty input by returning an empty list.
     * It then converts the Iterable returned by the repository into a List.
     *
     * @param reviewerIds the list of Reviewer IDs to fetch
     * @return a List of Reviewer objects that match the given IDs
     */
    public List<Reviewer> findAllById(List<Long> reviewerIds) {
        if (reviewerIds == null || reviewerIds.isEmpty()) {
            return new ArrayList<>();
        }
        Iterable<Reviewer> iterable = repository.findAllById(reviewerIds);
        List<Reviewer> result = new ArrayList<>();
        iterable.forEach(result::add);
        return result;
    }

    /**
     * Check if a Reviewer exists for the given ID.
     *
     * This method simply forwards the check to JpaRepository.
     *
     * @param id the primary key to check
     * @return true if a Reviewer with that ID exists, false otherwise
     */
    public boolean existsById(Long id) {
        // Delegates directly to `JpaRepository`.
        return repository.existsById(id);
    }
}
