package local.health.research.dao;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

import org.springframework.stereotype.Repository;

import local.health.research.models.Review;
import local.health.research.repositories.ReviewRepository;

/**
 * 
 * ReviewDao serves as a data-access object for Review entities.
 * It delegates all persistence operations to the ReviewRepository.
 * The @Repository annotation lets Spring treat this class as a
 * component that handles data storage and provides automatic
 * exception translation.
 */
@Repository
public class ReviewDao {

    // The JPA repository that actually talks to the database.
    private final ReviewRepository repository;

    /**
     * Constructor for ReviewDao.
     *
     * Spring injects the ReviewRepository bean automatically.
     *
     * @param repository the repository that handles Review entities
     */
    public ReviewDao(ReviewRepository repository) {
        this.repository = repository;
    }

    /**
     * Persist a Review entity (insert or update).
     *
     * @param review the Review to be saved
     * @return the saved Review, possibly with an autogenerated id
     */
    public Review save(Review review) {
        return repository.save(review);
    }

    /**
     * Retrieve all Review entities from the database.
     *
     * @return a List containing every Review
     */
    public List<Review> findAll() {
        return repository.findAll();
    }

    /**
     * Find a single Review by its primary key.
     *
     * @param id the Review's unique identifier
     * @return an Optional holding the Review if found,
     *         otherwise Optional.empty()
     */
    public Optional<Review> findById(Long id) {
        return repository.findById(id);
    }

    /**
     * Delete a Review identified by its ID.
     *
     * @param id the primary key of the Review to delete
     */
    public void deleteById(Long id) {
        repository.deleteById(id);
    }

    /**
     * Check if a Review exists for the given ID.
     *
     * This method simply forwards the check to JpaRepository.
     *
     * @param id the primary key to check
     * @return true if a Review with that ID exists, false otherwise
     */
    public boolean existsById(Long id) {
        // Delegates directly to JpaRepository.
        return repository.existsById(id);
    }

    /**
     * Finds all Review objects that belong to a specific article.
     * 
     * @param articleId the id of the article whose Reviews are requested
     * @return a List of Review objects
     */
    public List<Review> findByArticleId(Long articleId) {
        return repository.findByArticleId(articleId);
    }

    /**
     * Finds all Review objects that were written by a specific reviewer.
     * 
     * @param reviewerId the reviewer id is supplied as a parameter
     * @return a List of Review objects
     */
    public List<Review> findByReviewerId(Long reviewerId) {
        return repository.findByReviewerId(reviewerId);
    }

    /**
     * Retrieve a list of Reviews by a collection of ids.
     *
     * If the input list is null or empty, an empty list is returned.
     *
     * @param reviewIds a List of Review ids
     * @return a List of Review objects that match the provided ids
     */
    public List<Review> findAllById(List<Long> reviewIds) {
        if (reviewIds == null || reviewIds.isEmpty()) {
            return new ArrayList<>();
        }

        Iterable<Review> iterable = repository.findAllById(reviewIds);

        List<Review> reviews = new ArrayList<>();
        // Append each retrieved Review to the list.
        iterable.forEach(reviews::add);

        return reviews;
    }
}
